### ISSUE TITLE
Modularize lib crate with sub crates: sic edition

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#118]
- [x] Parser module & combostew re-export (issue: #119 , PR: #117)
- [x] module: help (issue: #121, PR: #122)
  - [x] remove ProcessWithConfig from crate (issue: #?, PR: #?)

**Future:**

Look into adding the combostew modules as crates in this repository. Publish these crates as appropriate on crates.io, use from sic with `path = ".../combostew_{X}"` :
-  combostew >> module: n_0
-  combostew >> module: n_1
-  combostew >> module: n_2
