### ISSUE TITLE
Re-integrate combostew as sub crates: combostew edition

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#125]
Re-integrate the [combostew](https://github.com/foresterre/combostew) modules in `sic`. They will be included as workspace crates.

First:
* [x] combostew: image engine => `sic_image_engine` (issue: #126  , PR: #127)

Second: `io+convert, config, testing`  (issue: #129, PR: #?): 
* [x] combostew: io => `sic_io`
* [x] combostew: config => `sic_config`
* [x] combostew: processor:
  * [x] license_display => `sic_lib`
  * [x] mod_test_includes => `sic_testing`
  * [x] conversion => `sic_io`
  * [x] encoding_format => `sic_io`
  * [x] Process(Mut)WithConfig: remove, only rework minimally to accommodate for this removal

Third:
- [x] Remove combostew from `sic_core`

Fourth:
* [x] Refactor some of the incorporated functionality to depend less on Config (issue #132)
  * [x] Remove dependency on `sic_config`

After completion
- [x] combostew: add deprecated message to readme

---

Status reports:
2019-07-07:
PR for re-integration of the  `image engine` module.

2019-07-08:
PR for re-integration of the  `image engine` module merged.

2019-07-08:
The `image engine` was very doable because it had no dependencies on other Combostew modules.
The other modules are a bit harder since there are dependencies on each other. Combostew included all functionality which was shared between [sic](https://github.com/foresterre/sic) and [stew](https://github.com/foresterre/stew). In hindsight this worked because it was made for just these two projects, however, the modules can be made more modular with less dependencies which allows functionality to be moved in and out more easily (like this re-integration). Especially, a few modules within Combostew depend on the `config` module, while they could have just taken the one or two values they needed as argument (or reference to). For example, the `conversion` module relies on `config` for the output format. The format should have been taken as argument instead. It currently takes `config` because it is build upon the ProcessWithConfig trait, which is currently not used as originally intended (to enable easier pipelining of individual stages).
All of the above makes it slightly harder to individually re-integrate the other Combostew modules individually. The cleaner way to integrate them would be to rework them within Combostew (less dependent on each other), release an update for Combostew, update sic to the new Combostew version and then cleanly re-integrate the modules as crates/modules within sic (rewriting a few imports).
However, since I will want to integrate these modules with sic anyway, since Combostew will be deprecated (if I will work on stew again, it could depend on `sic`'s workspace crates and since the rework within Combostew and updating of the rework within sic is more difficult if having to push updates to Combostew master (then the dependency in this repo would have to be on the Combostew git repo instead of the published crate) it might be worthwhile to instead directly re-integrate the remaining Combostew modules directly into sic.  

2019-07-09:
Decision to integrate `io+convert, config, testing` all at once.

2019-07-22:
Merged PR which refactored sic_io to not depend on Config 

2019-08-05:
Moved Config to sic_lib and refactored appropriately. This was the last dependency on sic_config, so it will be removed within this PR as well.
