### ISSUE TITLE
prepare release 0.11 with glob mode support

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#381]
TODO:
- [x] Add diff operation to image script (issue: #284)
- [x] Add glob mode (issue: #323 , pr: #379)
- [x] Add glob mode documentation (issue: #380)
