### ISSUE TITLE
Release 0.11 checklist

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#385]
RELEASE PR: #<PR NUMBER>

---

### Notable changes from `0.10` to `0.11`:
- ... (issue: #X, PR: #Y)
- ... (issue: #X, PR: #Y)
- ... (issue: #X, PR: #Y)

---

### Open issues

Blocking:
- [x] ... (issue: #X, PR: #Y)
- [x] ... (issue: #X, PR: #Y)
- [x] ... (issue: #X, PR: #Y)

---

### Release checklist

**Initialize release**

- [x] Create release issue. Already a step complete! :wink:
- [x] Create release branch ([branch](https://github.com/foresterre/sic/tree/release/v0.11))

**Update version number**

- [x] Define update version number [as described here](https://doc.rust-lang.org/cargo/reference/publishing.html#publishing-a-new-version-of-an-existing-crate).
- [x] Update the version number in all `Cargo.toml` files (i.e. all workspace crates).
    - Specifically, for the pre-1.0 versions the versioning strategy is currently as follows:
        - The minor version number is the same for all workspace crates, and incremented
          for each release. 
        - The patch version is increased on a as-needed basis, separately per crate. 
- The Clap App version number in `src/main.rs` will be equal to the version number in the root `Cargo.toml`.

**Update the dependency licenses to be included in the binary as per their licenses**

- [x] Run `cargo run --example update_dep_licenses` to update the licenses of dependencies, which will be included in a binary build.

**Create Release PR**

- [x] Create release PR 

**Verify**

- [x] Verify formatting with `cargo +nightly fmt`.
- [x] Does `cargo test` succeed?
- [x] Verify image output of images produced with `cargo test --features output-test-images`.
- [x] Do all CI runs complete successfully?
- [x] Are the versions indeed updated for all packages?
- [x] Is the application version updated?
- [x] Are the dependency licenses updated?

Completed!

**Merge Release PR**

If no blocking issues are detected and this checklist is complete,
we can move on to the next step.

**Publish & Upload**

- [x] Run `cargo package` and check the resulting `.crate`
- [x] Run `cargo publish` and verify the result

**Release, Tag & Binaries**

- [x] Write release notes

- [x] Create a release with a version tag on [the github release page](https://github.com/foresterre/sic/releases)
    - tags are equal to crate version number e.g. `0.5.1`
    - release title is `sic-<version>` e.g. `sic-0.5.1`

- [x] Add Windows and Linux binaries to the release
    - compile with `cargo build --release`

---

[Release steps](https://github.com/foresterre/sic/blob/master/RELEASE_STEPS.md)
