### ISSUE TITLE
Add `--no-skip-unsupported` which does not skip unsupported files in glob mode

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#407]
Use case:

Emboss example from the readme: `sic --mode glob -i "*" -o embossed_output -f png --filter3x3 -1 -1 0 -1 1 1 0 1 1`

This example works great if you have a flat folder containing only supported images files. e.g.

```
├── aaa.jpg
├── bbb.png
├── ccc.png
└── ddd.farbfeld
```

~~However as soon as we add a folder, e.g. `cmd_sensitive` in the example below, the command will fail as our iterator does not skip folders (perhaps we should!).~~ _fixed by #408_

```
├── aaa.jpg
├── bbb.png
├── ccc.png
└── cmd_sensitive
    ├── aaa.farbfeld 
    ├── bbb.farbfeld
    └── ccc.farbfeld
```

Another case where our program would fail is if it got unsupported file inputs, e.g. below `eee.foo` is an unsupported file type. 

```
├── aaa.jpg
├── bbb.png
├── ccc.png
└── eee.foo
```

The detail that makes it difficult to decide whether a file is supported or not is that we can't be sure until we do attempt to read a file (i.e. the extension itself doesn't make a file a certain type). We can take multiple routes, such as guessing the type by reading only the file header (this is something we already do, and the image crate does this too) or start by supporting this feature only for known file extensions (at first).

**Progress:**

* [x] Add `--no-skip-unsupported-extensions` (issue: #494, implemented by @MuLeonis)
* [ ] Add `--no-skip-unsupported-magic-bytes` (issue: #497, [relevant doc](https://docs.rs/image/0.23.4/image/fn.guess_format.html))  
* [ ] Add `--no-skip-unsupported` which will enable all `--skip-unsupported-(...)` flags
