### ISSUE TITLE
Add Avif image encoding support 

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#599]
- [x] Added Avif #590 
- [x] Update image crate to `>0.23.10`
  - [x] Remove Avif hack #597 
- ~~Verify encoding performance (had some very slow encoding results in development so far)~~ split to #661

**Comment by foresterre** [comment]
- [ ] Verify encoding performance  (had some very slow encoding results in development so far)
