### ISSUE TITLE
milestone planning: 1.0.0

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#615]
[Milestone Tracker](https://github.com/foresterre/sic/milestone/9)

What should be in before 1.0.0:
* [ ] unified parsing implemented #614  (current effort: sic_duo parser)
* [ ] Add image buffers #598
* [ ] Batch/Glob mode refactor to use image `buffers` #?
* [ ] Support units such as "%" #600
* [ ] Image Engine environment 
* [ ] Consistent user facing terminology (eg, batch/glob and better naming for cli ops and script)
* [ ] parallel multi buffer processing (with rayon?)
* [ ] Automated releasing and artefact building on the CI
* [ ] User documentation in one place (rustbook? readme? `--help` / `--user-manual`? or multiple of these with a shared text source)
* [ ] Examples with images for all operations in user facing documentation

Nice to haves:
* [ ] Image Engine refactor
* [ ] CI performance benchmarking (currently most time is by far spent in the image operations themselves; not parsing or other sic functionality; it would be nice to have performance numbers over time though!)
