### ISSUE TITLE
milestone planning: 0.15.0

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#616]
[Milestone Tracker](https://github.com/foresterre/sic/milestone/8)

#### User changes:

**Formats**
* [x] #599 Support TGA encoding
* [x] #599 Support AVIF encoding
  * [x] #590 Preliminary AVIF support
  * [x] #597 Remove AVIF implementation hack

#### Internal &amp; infra

_not listed_
