### ISSUE TITLE
milestone-planning: future

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#794]
## Milestones

**Milestone planning by version**
* v0.15 #616 (released)
* v0.16 #693 (released)
* v0.17 #773 

## Features not assigned to a milestone

**syntax**
* [ ] #600 support for units such as `%` and `px` with a default unit type

**image operations**
* [ ] #570 operation: vertical-gradient
* [ ] #571 operation: horizontal-gradient
* [ ] #547 operation: tiling
* [ ] #548 operation: dither

**UI**
* [ ] #todo Start with a first version of a GUI
