### ISSUE TITLE
milestone-planning: 0.18.0

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#797]
**[Milestone Tracker](https://github.com/foresterre/sic/milestone/12)**
[milestone-planning: roadmap](https://github.com/foresterre/sic/issues/794)

**Additions**
* [x] #798 Support setting repetitions in animated images (i.e. looping)

**Changes**
* [x] #800 Include imageproc-ops feature by default (i.e. draw-text will be included by default)

**Bug fixes**
* [x] #801 Fix automatic color type adjustment setting was ignored

**Comment by foresterre** [comment]
closed by #834
